### ISSUE TITLE
Remove incorrect and redundant identifiers from definitions

### ISSUE THREAD

**Issue by dragon-ai-agent** [ebi-chebi/ChEBI#4619]
```yaml
id: CHEBI:76579
name: triradylglycerol
def: "A glycerol compound having one of three possible substituent groups - either acyl, alkyl, or alk-1-enyl - at each of the three possible positions sn-1, sn-2 or sn-3. has functional parent glycerol (CHEBI:17754), children: triglyceride (CHEBI:17855). Parent: is_a glycerolipid (CHEBI:35741)" []
xref: LIPID_MAPS_class:LMGL0301
subset: 2_STAR
synonym: "triradylglycerols" RELATED [ChEBI]
is_a: CHEBI:35741 ! glycerolipid
```

Note the CHEBI definition randomly has mentions of other CHEBI terms. This is bad practice, as it is redundant and gets out of sync.

In this case the reported relationship "has functional parent glycerol (CHEBI:17754)" is untrue

it actually has two children, it's not clear why one is reported
